# Generated by Django 4.1.1 on 2023-03-17 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department_head', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='headdb',
            old_name='description',
            new_name='des',
        ),
        migrations.RenameField(
            model_name='headdb',
            old_name='profileimage',
            new_name='images',
        ),
    ]
