# Generated by Django 4.1.1 on 2023-03-17 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_head', '0003_employeedb'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedb',
            name='report',
            field=models.CharField(default='', max_length=30),
        ),
    ]
