# Generated by Django 4.1.1 on 2023-03-18 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department_head', '0004_employeedb_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='headdb',
            name='report',
            field=models.CharField(default='', max_length=30),
        ),
    ]
