# Generated by Django 3.2 on 2023-03-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departmentsdb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=30)),
                ('department_profileimage', models.ImageField(default='null.jpg', upload_to='Image')),
                ('year_founded', models.IntegerField()),
                ('description', models.CharField(max_length=30)),
            ],
        ),
    ]
