# Generated by Django 3.2 on 2023-03-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentsdb',
            old_name='department_name',
            new_name='departmentname',
        ),
        migrations.RenameField(
            model_name='departmentsdb',
            old_name='department_profileimage',
            new_name='profileimage',
        ),
        migrations.RenameField(
            model_name='departmentsdb',
            old_name='year_founded',
            new_name='yearfounded',
        ),
    ]
