# Generated by Django 4.1.1 on 2023-03-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_auto_20230317_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logindb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
