# Generated by Django 4.1.1 on 2023-03-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_logindb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentsdb',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
